version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: zildarius/wikipedia-telegram-bot:latest
    environment:
      CREATE_TABLE: "no"
      DB_SWITCH: "on"
      TOKEN: 5302735752:AAGsAffMWEwycRSZvt-iOCKrEI2dyT2uo2o
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
